'use strict';

module.exports = {
  settlement:
    require('./settlementEngineV10.js'),
  retention:
    require('./retentionEngineV10.js'),
  staff:
    require('./staffOperationsEngineV10.js'),
  staffManagement:
    require('./staffManagementCoordinatorV0823.js'),
  live:
    require('./liveOperationsCoordinatorV0824.js'),
  delivery:
    require('./deliveryEngineV10.js'),
  marketing:
    require('./marketingEngineV10.js'),
  marketingPlatformMembership:
    require('./marketingPlatformMembershipV0826.js'),
  brand:
    require('./brandGrowthEngineV10.js'),
  events:
    require('./restaurantEventEngineV10.js'),
  runtime:
    require('./restaurantRuntimeV10.js'),
  finance:
    require('../finance/completeFinanceSystemV0825.js'),
  reputation:
    require('../reputation/reputationMediaSystemV0827.js'),
  commercialEcology:
    require('../world/commercialEcologySystemV0828.js'),
  environment:
    require('../world/environmentWorldCoordinatorV0829.js'),
  regulatory:
    require('../regulatory/regulatoryFoodSafetySystemV0830.js'),
  social:
    require('../social/socialInteractionSystemV0831.js'),
  random:
    require('../core/globalRandomEngineV0832.js'),
  growth:
    require('../progress/growthAchievementSystemV0833.js'),
  multiStoreBrand:
    require('../brand/multiStoreBrandRankingV0834.js'),
  dailyCycle:
    require('./dailyOperatingCycleV0840.js'),
  decisionFeedback:
    require('./decisionFeedbackV0841.js'),
  playtestHealth:
    require('../diagnostics/playtestHealthV0842.js'),
  balanceTuner:
    require('../balance/operatingBalanceTunerV0843.js')
};
