"use strict";

/**
 * 餐饮商铺基础数据库 V1
 *
 * 设计原则：
 * 1. 数据与逻辑分离，后面扩充商圈、街道、铺型时只追加数据。
 * 2. 所有可统计字段使用明确数值，不用“较高/较低”代替。
 * 3. 商铺不是住宅，“户型”使用商业铺型：开间、转角、前店后厨、双层等。
 * 4. 后续动态市场、NPC 抢租、房东谈判都可以直接基于这些字段扩展。
 */

const DISTRICT_PROFILES = {
  university: {
    id: "university",
    name: "大学城",
    character: "校园消费",
    demandPattern: "午餐、晚餐、夜宵集中",
    averageRentFactor: 0.82,
    vacancyRate: 0.072,
    newListingRate: 0.13,
    takeawayRatio: 0.46,
    weekendFactor: 0.88,
    nightFactor: 1.26,
  },

  cbd: {
    id: "cbd",
    name: "商业中心",
    character: "高客单商务消费",
    demandPattern: "工作日午餐爆发，晚餐商务需求稳定",
    averageRentFactor: 1.28,
    vacancyRate: 0.041,
    newListingRate: 0.09,
    takeawayRatio: 0.31,
    weekendFactor: 0.74,
    nightFactor: 0.92,
  },

  hightech: {
    id: "hightech",
    name: "高新区",
    character: "科技园与新社区",
    demandPattern: "工作日午餐强，社区晚餐增长快",
    averageRentFactor: 1.02,
    vacancyRate: 0.066,
    newListingRate: 0.16,
    takeawayRatio: 0.42,
    weekendFactor: 0.79,
    nightFactor: 0.86,
  },

  oldtown: {
    id: "oldtown",
    name: "老城区",
    character: "居民熟客型消费",
    demandPattern: "早餐与晚餐稳定，复购率高",
    averageRentFactor: 0.72,
    vacancyRate: 0.058,
    newListingRate: 0.08,
    takeawayRatio: 0.27,
    weekendFactor: 1.08,
    nightFactor: 0.84,
  },

  village: {
    id: "village",
    name: "城中村",
    character: "低价高频生活消费",
    demandPattern: "早餐、晚餐、夜宵强",
    averageRentFactor: 0.54,
    vacancyRate: 0.094,
    newListingRate: 0.18,
    takeawayRatio: 0.51,
    weekendFactor: 1.04,
    nightFactor: 1.38,
  },

  market: {
    id: "market",
    name: "东门市场",
    character: "商贩与居民混合消费",
    demandPattern: "清晨与午餐强，闭市后快速回落",
    averageRentFactor: 0.63,
    vacancyRate: 0.081,
    newListingRate: 0.12,
    takeawayRatio: 0.24,
    weekendFactor: 1.12,
    nightFactor: 0.61,
  },

  industry: {
    id: "industry",
    name: "工业园",
    character: "工厂与物流园刚需",
    demandPattern: "午餐集中，早晚班形成第二波需求",
    averageRentFactor: 0.59,
    vacancyRate: 0.087,
    newListingRate: 0.14,
    takeawayRatio: 0.39,
    weekendFactor: 0.67,
    nightFactor: 0.78,
  },
};

/**
 * 每个商圈 6 条街道，共 42 条。
 *
 * 字段：
 * - traffic：自然人流指数 0~100
 * - vehicleTraffic：车流指数 0~100
 * - competition：餐饮竞争指数 0~100
 * - rentFactor：相对本商圈租金倍率
 * - delivery：外卖骑手便利指数
 * - parking：停车便利指数
 * - night：夜间消费指数
 * - office / resident / student / worker：主要客群强度
 */
const STREETS = [
  // 大学城
  {
    id: "uni_xuefu",
    districtId: "university",
    name: "学府路",
    type: "校园主街",
    traffic: 94,
    vehicleTraffic: 48,
    competition: 91,
    rentFactor: 1.18,
    delivery: 91,
    parking: 43,
    night: 86,
    office: 18,
    resident: 38,
    student: 100,
    worker: 12,
  },
  {
    id: "uni_qingnian",
    districtId: "university",
    name: "青年街",
    type: "生活商业街",
    traffic: 88,
    vehicleTraffic: 52,
    competition: 84,
    rentFactor: 1.02,
    delivery: 93,
    parking: 46,
    night: 96,
    office: 14,
    resident: 61,
    student: 92,
    worker: 19,
  },
  {
    id: "uni_nanyuan",
    districtId: "university",
    name: "南苑路",
    type: "宿舍生活圈",
    traffic: 79,
    vehicleTraffic: 41,
    competition: 73,
    rentFactor: 0.86,
    delivery: 88,
    parking: 38,
    night: 91,
    office: 8,
    resident: 57,
    student: 89,
    worker: 15,
  },
  {
    id: "uni_tiyu",
    districtId: "university",
    name: "体育馆路",
    type: "赛事活动街",
    traffic: 71,
    vehicleTraffic: 67,
    competition: 58,
    rentFactor: 0.91,
    delivery: 72,
    parking: 74,
    night: 73,
    office: 17,
    resident: 36,
    student: 78,
    worker: 9,
  },
  {
    id: "uni_shuyuan",
    districtId: "university",
    name: "书院街",
    type: "文教社区街",
    traffic: 68,
    vehicleTraffic: 36,
    competition: 61,
    rentFactor: 0.79,
    delivery: 84,
    parking: 31,
    night: 64,
    office: 22,
    resident: 62,
    student: 74,
    worker: 11,
  },
  {
    id: "uni_ximen",
    districtId: "university",
    name: "西门巷",
    type: "校门小吃街",
    traffic: 90,
    vehicleTraffic: 24,
    competition: 95,
    rentFactor: 1.09,
    delivery: 96,
    parking: 18,
    night: 100,
    office: 7,
    resident: 43,
    student: 100,
    worker: 21,
  },

  // 商业中心
  {
    id: "cbd_finance",
    districtId: "cbd",
    name: "金融大道",
    type: "核心写字楼街",
    traffic: 98,
    vehicleTraffic: 89,
    competition: 96,
    rentFactor: 1.32,
    delivery: 78,
    parking: 62,
    night: 71,
    office: 100,
    resident: 22,
    student: 3,
    worker: 36,
  },
  {
    id: "cbd_central",
    districtId: "cbd",
    name: "中央街",
    type: "综合商业街",
    traffic: 96,
    vehicleTraffic: 76,
    competition: 94,
    rentFactor: 1.25,
    delivery: 82,
    parking: 58,
    night: 88,
    office: 91,
    resident: 34,
    student: 8,
    worker: 27,
  },
  {
    id: "cbd_riverside",
    districtId: "cbd",
    name: "滨河路",
    type: "夜间消费带",
    traffic: 84,
    vehicleTraffic: 64,
    competition: 81,
    rentFactor: 1.04,
    delivery: 75,
    parking: 69,
    night: 98,
    office: 58,
    resident: 49,
    student: 9,
    worker: 16,
  },
  {
    id: "cbd_plaza",
    districtId: "cbd",
    name: "时代广场街",
    type: "商场集群",
    traffic: 99,
    vehicleTraffic: 71,
    competition: 100,
    rentFactor: 1.41,
    delivery: 66,
    parking: 81,
    night: 92,
    office: 82,
    resident: 29,
    student: 11,
    worker: 25,
  },
  {
    id: "cbd_station",
    districtId: "cbd",
    name: "枢纽南路",
    type: "交通枢纽商业",
    traffic: 93,
    vehicleTraffic: 98,
    competition: 86,
    rentFactor: 1.16,
    delivery: 73,
    parking: 54,
    night: 83,
    office: 71,
    resident: 21,
    student: 13,
    worker: 49,
  },
  {
    id: "cbd_backstreet",
    districtId: "cbd",
    name: "万象后街",
    type: "写字楼后街",
    traffic: 78,
    vehicleTraffic: 39,
    competition: 76,
    rentFactor: 0.88,
    delivery: 94,
    parking: 33,
    night: 69,
    office: 89,
    resident: 31,
    student: 6,
    worker: 39,
  },

  // 高新区
  {
    id: "ht_kechuang",
    districtId: "hightech",
    name: "科创大道",
    type: "科技办公街",
    traffic: 91,
    vehicleTraffic: 83,
    competition: 84,
    rentFactor: 1.13,
    delivery: 87,
    parking: 76,
    night: 72,
    office: 100,
    resident: 27,
    student: 4,
    worker: 48,
  },
  {
    id: "ht_software",
    districtId: "hightech",
    name: "软件园路",
    type: "园区配套街",
    traffic: 84,
    vehicleTraffic: 71,
    competition: 72,
    rentFactor: 0.97,
    delivery: 91,
    parking: 82,
    night: 61,
    office: 94,
    resident: 22,
    student: 5,
    worker: 53,
  },
  {
    id: "ht_zhigu",
    districtId: "hightech",
    name: "智谷街",
    type: "新社区商业",
    traffic: 73,
    vehicleTraffic: 68,
    competition: 59,
    rentFactor: 0.82,
    delivery: 86,
    parking: 77,
    night: 68,
    office: 64,
    resident: 76,
    student: 7,
    worker: 31,
  },
  {
    id: "ht_chuangye",
    districtId: "hightech",
    name: "创业路",
    type: "孵化器街区",
    traffic: 78,
    vehicleTraffic: 61,
    competition: 66,
    rentFactor: 0.89,
    delivery: 92,
    parking: 70,
    night: 74,
    office: 88,
    resident: 35,
    student: 12,
    worker: 33,
  },
  {
    id: "ht_hupan",
    districtId: "hightech",
    name: "湖畔街",
    type: "品质社区街",
    traffic: 69,
    vehicleTraffic: 57,
    competition: 55,
    rentFactor: 0.93,
    delivery: 79,
    parking: 84,
    night: 79,
    office: 49,
    resident: 92,
    student: 6,
    worker: 17,
  },
  {
    id: "ht_metro",
    districtId: "hightech",
    name: "地铁科技城站前街",
    type: "轨道站点商业",
    traffic: 89,
    vehicleTraffic: 58,
    competition: 78,
    rentFactor: 1.06,
    delivery: 88,
    parking: 55,
    night: 77,
    office: 86,
    resident: 54,
    student: 8,
    worker: 42,
  },

  // 老城区
  {
    id: "old_jiefang",
    districtId: "oldtown",
    name: "解放路",
    type: "老城主街",
    traffic: 84,
    vehicleTraffic: 67,
    competition: 78,
    rentFactor: 1.08,
    delivery: 75,
    parking: 35,
    night: 69,
    office: 24,
    resident: 100,
    student: 13,
    worker: 32,
  },
  {
    id: "old_changle",
    districtId: "oldtown",
    name: "长乐街",
    type: "社区餐饮街",
    traffic: 78,
    vehicleTraffic: 43,
    competition: 71,
    rentFactor: 0.88,
    delivery: 82,
    parking: 29,
    night: 73,
    office: 13,
    resident: 96,
    student: 11,
    worker: 29,
  },
  {
    id: "old_beimen",
    districtId: "oldtown",
    name: "北门巷",
    type: "老街巷口",
    traffic: 64,
    vehicleTraffic: 22,
    competition: 51,
    rentFactor: 0.64,
    delivery: 61,
    parking: 17,
    night: 58,
    office: 6,
    resident: 91,
    student: 8,
    worker: 18,
  },
  {
    id: "old_miaoqian",
    districtId: "oldtown",
    name: "庙前街",
    type: "传统商业街",
    traffic: 88,
    vehicleTraffic: 31,
    competition: 82,
    rentFactor: 1.01,
    delivery: 69,
    parking: 21,
    night: 82,
    office: 9,
    resident: 88,
    student: 14,
    worker: 26,
  },
  {
    id: "old_xihe",
    districtId: "oldtown",
    name: "西河路",
    type: "滨水居民街",
    traffic: 70,
    vehicleTraffic: 56,
    competition: 57,
    rentFactor: 0.73,
    delivery: 77,
    parking: 48,
    night: 64,
    office: 11,
    resident: 94,
    student: 8,
    worker: 20,
  },
  {
    id: "old_hospital",
    districtId: "oldtown",
    name: "人民医院街",
    type: "医院周边商业",
    traffic: 86,
    vehicleTraffic: 72,
    competition: 74,
    rentFactor: 0.96,
    delivery: 88,
    parking: 42,
    night: 76,
    office: 28,
    resident: 71,
    student: 5,
    worker: 44,
  },

  // 城中村
  {
    id: "vil_xinmin",
    districtId: "village",
    name: "新民街",
    type: "城中村主街",
    traffic: 91,
    vehicleTraffic: 46,
    competition: 84,
    rentFactor: 1.05,
    delivery: 96,
    parking: 27,
    night: 100,
    office: 12,
    resident: 95,
    student: 31,
    worker: 83,
  },
  {
    id: "vil_chengnan",
    districtId: "village",
    name: "城南路",
    type: "通勤道路",
    traffic: 81,
    vehicleTraffic: 79,
    competition: 68,
    rentFactor: 0.88,
    delivery: 91,
    parking: 51,
    night: 82,
    office: 9,
    resident: 78,
    student: 22,
    worker: 94,
  },
  {
    id: "vil_anju",
    districtId: "village",
    name: "安居巷",
    type: "租住生活区",
    traffic: 69,
    vehicleTraffic: 23,
    competition: 54,
    rentFactor: 0.69,
    delivery: 83,
    parking: 20,
    night: 87,
    office: 5,
    resident: 100,
    student: 26,
    worker: 72,
  },
  {
    id: "vil_night",
    districtId: "village",
    name: "夜市街",
    type: "夜间摊店街",
    traffic: 77,
    vehicleTraffic: 19,
    competition: 92,
    rentFactor: 0.97,
    delivery: 88,
    parking: 14,
    night: 100,
    office: 4,
    resident: 83,
    student: 38,
    worker: 79,
  },
  {
    id: "vil_factory",
    districtId: "village",
    name: "厂前路",
    type: "工厂生活街",
    traffic: 75,
    vehicleTraffic: 61,
    competition: 63,
    rentFactor: 0.76,
    delivery: 87,
    parking: 47,
    night: 72,
    office: 6,
    resident: 69,
    student: 14,
    worker: 100,
  },
  {
    id: "vil_bridge",
    districtId: "village",
    name: "桥头街",
    type: "交通节点商业",
    traffic: 83,
    vehicleTraffic: 91,
    competition: 70,
    rentFactor: 0.84,
    delivery: 79,
    parking: 44,
    night: 79,
    office: 7,
    resident: 75,
    student: 18,
    worker: 86,
  },

  // 东门市场
  {
    id: "mkt_dongmen",
    districtId: "market",
    name: "东门街",
    type: "市场入口街",
    traffic: 96,
    vehicleTraffic: 61,
    competition: 87,
    rentFactor: 1.12,
    delivery: 79,
    parking: 31,
    night: 54,
    office: 5,
    resident: 78,
    student: 8,
    worker: 74,
  },
  {
    id: "mkt_trade",
    districtId: "market",
    name: "商贸路",
    type: "批发配套街",
    traffic: 86,
    vehicleTraffic: 92,
    competition: 71,
    rentFactor: 0.91,
    delivery: 81,
    parking: 67,
    night: 49,
    office: 8,
    resident: 56,
    student: 3,
    worker: 91,
  },
  {
    id: "mkt_caishi",
    districtId: "market",
    name: "菜市巷",
    type: "居民菜市场街",
    traffic: 74,
    vehicleTraffic: 34,
    competition: 59,
    rentFactor: 0.72,
    delivery: 63,
    parking: 23,
    night: 42,
    office: 3,
    resident: 100,
    student: 7,
    worker: 53,
  },
  {
    id: "mkt_fresh",
    districtId: "market",
    name: "鲜活水产街",
    type: "专业市场街",
    traffic: 82,
    vehicleTraffic: 77,
    competition: 65,
    rentFactor: 0.86,
    delivery: 58,
    parking: 52,
    night: 38,
    office: 3,
    resident: 61,
    student: 2,
    worker: 88,
  },
  {
    id: "mkt_station",
    districtId: "market",
    name: "货运站路",
    type: "物流配套街",
    traffic: 72,
    vehicleTraffic: 100,
    competition: 48,
    rentFactor: 0.67,
    delivery: 72,
    parking: 81,
    night: 57,
    office: 4,
    resident: 37,
    student: 1,
    worker: 100,
  },
  {
    id: "mkt_south",
    districtId: "market",
    name: "南市口",
    type: "居民商业口",
    traffic: 79,
    vehicleTraffic: 57,
    competition: 69,
    rentFactor: 0.83,
    delivery: 84,
    parking: 39,
    night: 64,
    office: 6,
    resident: 94,
    student: 9,
    worker: 58,
  },

  // 工业园
  {
    id: "ind_xingye",
    districtId: "industry",
    name: "兴业路",
    type: "工厂主干道",
    traffic: 87,
    vehicleTraffic: 89,
    competition: 71,
    rentFactor: 1.04,
    delivery: 84,
    parking: 74,
    night: 65,
    office: 13,
    resident: 24,
    student: 1,
    worker: 100,
  },
  {
    id: "ind_logistics",
    districtId: "industry",
    name: "物流大道",
    type: "物流园配套",
    traffic: 80,
    vehicleTraffic: 100,
    competition: 59,
    rentFactor: 0.91,
    delivery: 72,
    parking: 93,
    night: 74,
    office: 8,
    resident: 17,
    student: 1,
    worker: 100,
  },
  {
    id: "ind_worker",
    districtId: "industry",
    name: "工人路",
    type: "宿舍生活街",
    traffic: 74,
    vehicleTraffic: 51,
    competition: 51,
    rentFactor: 0.79,
    delivery: 88,
    parking: 58,
    night: 83,
    office: 7,
    resident: 73,
    student: 3,
    worker: 98,
  },
  {
    id: "ind_east",
    districtId: "industry",
    name: "东厂街",
    type: "制造企业配套街",
    traffic: 68,
    vehicleTraffic: 82,
    competition: 44,
    rentFactor: 0.71,
    delivery: 76,
    parking: 88,
    night: 48,
    office: 10,
    resident: 14,
    student: 0,
    worker: 95,
  },
  {
    id: "ind_gate",
    districtId: "industry",
    name: "园区北门街",
    type: "园区入口商业",
    traffic: 89,
    vehicleTraffic: 94,
    competition: 76,
    rentFactor: 1.09,
    delivery: 82,
    parking: 69,
    night: 69,
    office: 17,
    resident: 29,
    student: 1,
    worker: 100,
  },
  {
    id: "ind_service",
    districtId: "industry",
    name: "综合服务街",
    type: "园区生活中心",
    traffic: 82,
    vehicleTraffic: 66,
    competition: 68,
    rentFactor: 0.98,
    delivery: 91,
    parking: 77,
    night: 78,
    office: 24,
    resident: 41,
    student: 2,
    worker: 94,
  },
];

const PROPERTY_TYPES = [
  {
    id: "street_shop",
    name: "临街底商",
    minArea: 28,
    maxArea: 180,
    floorOptions: ["1层"],
    frontageMin: 3.2,
    frontageMax: 9.0,
    visibilityBonus: 12,
    rentFactor: 1.08,
  },
  {
    id: "corner_shop",
    name: "转角铺",
    minArea: 45,
    maxArea: 220,
    floorOptions: ["1层"],
    frontageMin: 6.0,
    frontageMax: 15.0,
    visibilityBonus: 22,
    rentFactor: 1.22,
  },
  {
    id: "community_shop",
    name: "社区底商",
    minArea: 35,
    maxArea: 160,
    floorOptions: ["1层"],
    frontageMin: 3.5,
    frontageMax: 8.5,
    visibilityBonus: 7,
    rentFactor: 0.92,
  },
  {
    id: "mall_shop",
    name: "商场内铺",
    minArea: 30,
    maxArea: 260,
    floorOptions: ["B1", "1层", "2层", "3层"],
    frontageMin: 3.0,
    frontageMax: 10.0,
    visibilityBonus: 9,
    rentFactor: 1.18,
  },
  {
    id: "foodcourt_stall",
    name: "美食城档口",
    minArea: 12,
    maxArea: 45,
    floorOptions: ["B1", "1层", "2层", "3层"],
    frontageMin: 2.2,
    frontageMax: 5.0,
    visibilityBonus: 5,
    rentFactor: 0.74,
  },
  {
    id: "office_podium",
    name: "写字楼裙房",
    minArea: 45,
    maxArea: 210,
    floorOptions: ["1层", "2层"],
    frontageMin: 3.8,
    frontageMax: 10.0,
    visibilityBonus: 10,
    rentFactor: 1.12,
  },
  {
    id: "market_shop",
    name: "市场门面",
    minArea: 18,
    maxArea: 95,
    floorOptions: ["1层"],
    frontageMin: 2.5,
    frontageMax: 6.5,
    visibilityBonus: 4,
    rentFactor: 0.79,
  },
  {
    id: "village_shop",
    name: "城中村沿街铺",
    minArea: 22,
    maxArea: 130,
    floorOptions: ["1层", "1-2层"],
    frontageMin: 2.8,
    frontageMax: 7.0,
    visibilityBonus: 3,
    rentFactor: 0.66,
  },
  {
    id: "detached",
    name: "独栋餐饮铺",
    minArea: 120,
    maxArea: 520,
    floorOptions: ["1层", "1-2层", "1-3层"],
    frontageMin: 7.0,
    frontageMax: 22.0,
    visibilityBonus: 18,
    rentFactor: 1.04,
  },
  {
    id: "duplex",
    name: "双层街铺",
    minArea: 80,
    maxArea: 300,
    floorOptions: ["1-2层"],
    frontageMin: 4.5,
    frontageMax: 11.0,
    visibilityBonus: 8,
    rentFactor: 0.91,
  },
  {
    id: "station_shop",
    name: "交通枢纽铺",
    minArea: 20,
    maxArea: 130,
    floorOptions: ["B1", "1层", "2层"],
    frontageMin: 2.8,
    frontageMax: 7.5,
    visibilityBonus: 15,
    rentFactor: 1.26,
  },
  {
    id: "park_canteen",
    name: "园区餐饮档口",
    minArea: 20,
    maxArea: 90,
    floorOptions: ["1层", "2层"],
    frontageMin: 2.5,
    frontageMax: 6.0,
    visibilityBonus: 2,
    rentFactor: 0.68,
  },
];

const LAYOUT_TYPES = [
  {
    id: "single_bay",
    name: "单开间",
    usableRatio: 0.9,
    kitchenEase: 62,
    seatsFactor: 0.64,
  },
  {
    id: "double_bay",
    name: "双开间",
    usableRatio: 0.92,
    kitchenEase: 78,
    seatsFactor: 0.72,
  },
  {
    id: "long_narrow",
    name: "狭长型",
    usableRatio: 0.87,
    kitchenEase: 55,
    seatsFactor: 0.57,
  },
  {
    id: "front_back",
    name: "前店后厨",
    usableRatio: 0.91,
    kitchenEase: 94,
    seatsFactor: 0.66,
  },
  {
    id: "corner_l",
    name: "L型转角",
    usableRatio: 0.86,
    kitchenEase: 68,
    seatsFactor: 0.63,
  },
  {
    id: "through_shop",
    name: "前后通铺",
    usableRatio: 0.93,
    kitchenEase: 88,
    seatsFactor: 0.69,
  },
  {
    id: "duplex_layout",
    name: "上下两层",
    usableRatio: 0.82,
    kitchenEase: 59,
    seatsFactor: 0.75,
  },
  {
    id: "high_ceiling",
    name: "挑高开间",
    usableRatio: 0.89,
    kitchenEase: 71,
    seatsFactor: 0.67,
  },
  {
    id: "mall_rect",
    name: "商场矩形铺",
    usableRatio: 0.94,
    kitchenEase: 73,
    seatsFactor: 0.7,
  },
  {
    id: "stall",
    name: "档口型",
    usableRatio: 0.96,
    kitchenEase: 82,
    seatsFactor: 0.18,
  },
];

const PREVIOUS_BUSINESS_TYPES = [
  "中式快餐",
  "面馆",
  "米粉店",
  "火锅店",
  "烧烤店",
  "奶茶店",
  "咖啡店",
  "便利店",
  "早餐加盟",
  "烘焙店",
  "川湘菜馆",
  "日式简餐",
  "空置毛坯",
];

const VACANCY_REASONS = [
  "原租户合同到期",
  "原店经营亏损退出",
  "房东主动收回重新出租",
  "品牌迁址",
  "原店面积不足升级搬迁",
  "物业业态调整",
  "原店转让未成交后退租",
];

const RISK_LIBRARY = [
  { id: "none", name: "无明显硬伤", level: 0, costImpact: 0 },
  { id: "exhaust_rework", name: "排烟管道需整改", level: 2, costImpact: 12000 },
  { id: "drainage", name: "后厨排水需要改造", level: 2, costImpact: 9000 },
  { id: "power", name: "现有电容不足", level: 2, costImpact: 7000 },
  { id: "gas_limit", name: "天然气增容审批较慢", level: 2, costImpact: 5000 },
  { id: "sign_limit", name: "门头招牌尺寸受限制", level: 1, costImpact: 2500 },
  { id: "noise", name: "楼上居民对夜间噪音敏感", level: 2, costImpact: 0 },
  { id: "parking", name: "门前停车条件差", level: 1, costImpact: 0 },
  {
    id: "landlord_sale",
    name: "房东未来两年存在出售意向",
    level: 3,
    costImpact: 0,
  },
  { id: "roadwork", name: "门前道路计划施工", level: 3, costImpact: 0 },
  { id: "fire", name: "消防喷淋需要补点", level: 2, costImpact: 8000 },
  { id: "grease", name: "隔油设施不达标", level: 2, costImpact: 6500 },
];

const LANDLORD_PROFILES = [
  {
    id: "stable_personal",
    name: "稳健型个人房东",
    negotiation: 58,
    renewalRisk: 22,
    inspectionStrictness: 46,
  },
  {
    id: "price_personal",
    name: "价格敏感型个人房东",
    negotiation: 74,
    renewalRisk: 38,
    inspectionStrictness: 39,
  },
  {
    id: "commercial_company",
    name: "商业运营公司",
    negotiation: 31,
    renewalRisk: 16,
    inspectionStrictness: 84,
  },
  {
    id: "second_landlord",
    name: "二房东转租",
    negotiation: 66,
    renewalRisk: 67,
    inspectionStrictness: 28,
  },
  {
    id: "family_owner",
    name: "家庭共同持有",
    negotiation: 47,
    renewalRisk: 44,
    inspectionStrictness: 52,
  },
  {
    id: "asset_company",
    name: "资产管理公司",
    negotiation: 24,
    renewalRisk: 18,
    inspectionStrictness: 91,
  },
];

const BROKERS = [
  {
    id: "broker_chen",
    name: "陈启明",
    age: 34,
    agency: "海城商业地产",
    reliability: 86,
    feeRate: 0.5,
    specialty: "临街餐饮铺",
    inventoryStrength: 89,
    negotiation: 76,
  },
  {
    id: "broker_zhou",
    name: "周婉宁",
    age: 29,
    agency: "安居商业",
    reliability: 78,
    feeRate: 0.4,
    specialty: "校园与社区商铺",
    inventoryStrength: 82,
    negotiation: 69,
  },
  {
    id: "broker_luo",
    name: "罗志强",
    age: 42,
    agency: "百汇商铺中心",
    reliability: 92,
    feeRate: 0.65,
    specialty: "餐饮转让铺",
    inventoryStrength: 91,
    negotiation: 88,
  },
  {
    id: "broker_he",
    name: "何远航",
    age: 38,
    agency: "城市铺网",
    reliability: 73,
    feeRate: 0.35,
    specialty: "工业园与市场门面",
    inventoryStrength: 85,
    negotiation: 63,
  },
  {
    id: "broker_sun",
    name: "孙雅琴",
    age: 31,
    agency: "万铺联行",
    reliability: 88,
    feeRate: 0.55,
    specialty: "商场与写字楼商业",
    inventoryStrength: 87,
    negotiation: 81,
  },
  {
    id: "broker_ma",
    name: "马国梁",
    age: 46,
    agency: "本地商铺通",
    reliability: 81,
    feeRate: 0.45,
    specialty: "老城区与城中村商铺",
    inventoryStrength: 93,
    negotiation: 84,
  },
];

const PAYMENT_CYCLES = [
  { id: "monthly", name: "押后月付", monthsPerPayment: 1, rentDiscount: 0 },
  {
    id: "quarterly",
    name: "押后季付",
    monthsPerPayment: 3,
    rentDiscount: 0.01,
  },
  { id: "halfyear", name: "半年付", monthsPerPayment: 6, rentDiscount: 0.025 },
];

module.exports = {
  DISTRICT_PROFILES,
  STREETS,
  PROPERTY_TYPES,
  LAYOUT_TYPES,
  PREVIOUS_BUSINESS_TYPES,
  VACANCY_REASONS,
  RISK_LIBRARY,
  LANDLORD_PROFILES,
  BROKERS,
  PAYMENT_CYCLES,
};
