"use strict";

/**
 * 动态商铺市场数据
 *
 * 这里只放“规则素材”，不放每天固定结果。
 * 每天发生什么由 propertyMarketSystem 根据市场状态、街道数据、
 * 房源条件、NPC 竞争和事件动态计算。
 */

const CONFIG = {
  version: 1,

  // 每条街道拥有 18 个潜在商铺槽位。
  // 42 条街道 => 756 个潜在地址。
  potentialSlotsPerStreet: 18,

  // 实际挂牌量会动态浮动，并不会 756 套同时出售/出租。
  minActiveListingsPerStreet: 3,
  maxActiveListingsPerStreet: 12,

  // 历史记录上限，防止长期运行无限膨胀。
  maxHistoryItems: 600,

  // 市场事件同时存在数量限制。
  maxActiveEvents: 8,
};

const TENANT_ARCHETYPES = [
  {
    id: "fast_food_beginner",
    name: "小型快餐创业者",
    budgetMin: 50000,
    budgetMax: 180000,
    areaMin: 35,
    areaMax: 120,
    preferred: ["street_shop", "community_shop", "village_shop"],
    requireExhaust: true,
    requireGas: false,
    priceSensitivity: 88,
    locationSensitivity: 62,
  },
  {
    id: "drink_chain",
    name: "饮品连锁拓店组",
    budgetMin: 100000,
    budgetMax: 420000,
    areaMin: 20,
    areaMax: 85,
    preferred: ["street_shop", "corner_shop", "mall_shop", "station_shop"],
    requireExhaust: false,
    requireGas: false,
    priceSensitivity: 52,
    locationSensitivity: 95,
  },
  {
    id: "noodle_owner",
    name: "面馆经营者",
    budgetMin: 70000,
    budgetMax: 260000,
    areaMin: 40,
    areaMax: 130,
    preferred: ["street_shop", "community_shop", "market_shop", "village_shop"],
    requireExhaust: true,
    requireGas: true,
    priceSensitivity: 79,
    locationSensitivity: 70,
  },
  {
    id: "bbq_team",
    name: "烧烤创业团队",
    budgetMin: 130000,
    budgetMax: 480000,
    areaMin: 80,
    areaMax: 210,
    preferred: ["street_shop", "corner_shop", "detached", "duplex"],
    requireExhaust: true,
    requireGas: true,
    priceSensitivity: 68,
    locationSensitivity: 77,
  },
  {
    id: "hotpot_chain",
    name: "火锅品牌拓店组",
    budgetMin: 420000,
    budgetMax: 1500000,
    areaMin: 160,
    areaMax: 520,
    preferred: ["detached", "corner_shop", "mall_shop", "duplex"],
    requireExhaust: true,
    requireGas: false,
    priceSensitivity: 35,
    locationSensitivity: 92,
  },
  {
    id: "coffee_brand",
    name: "咖啡品牌拓店组",
    budgetMin: 180000,
    budgetMax: 760000,
    areaMin: 45,
    areaMax: 180,
    preferred: ["corner_shop", "mall_shop", "office_podium", "street_shop"],
    requireExhaust: false,
    requireGas: false,
    priceSensitivity: 44,
    locationSensitivity: 91,
  },
  {
    id: "community_restaurant",
    name: "社区餐馆经营者",
    budgetMin: 120000,
    budgetMax: 520000,
    areaMin: 80,
    areaMax: 240,
    preferred: ["community_shop", "street_shop", "duplex"],
    requireExhaust: true,
    requireGas: true,
    priceSensitivity: 75,
    locationSensitivity: 66,
  },
  {
    id: "foodcourt_operator",
    name: "档口经营者",
    budgetMin: 30000,
    budgetMax: 120000,
    areaMin: 12,
    areaMax: 50,
    preferred: ["foodcourt_stall", "park_canteen", "market_shop"],
    requireExhaust: false,
    requireGas: false,
    priceSensitivity: 92,
    locationSensitivity: 58,
  },
  {
    id: "premium_restaurant",
    name: "品质正餐团队",
    budgetMin: 550000,
    budgetMax: 2200000,
    areaMin: 180,
    areaMax: 520,
    preferred: ["detached", "mall_shop", "corner_shop", "office_podium"],
    requireExhaust: true,
    requireGas: true,
    priceSensitivity: 26,
    locationSensitivity: 96,
  },
  {
    id: "delivery_kitchen",
    name: "外卖厨房经营者",
    budgetMin: 60000,
    budgetMax: 260000,
    areaMin: 35,
    areaMax: 130,
    preferred: [
      "village_shop",
      "community_shop",
      "park_canteen",
      "market_shop",
    ],
    requireExhaust: true,
    requireGas: false,
    priceSensitivity: 93,
    locationSensitivity: 48,
  },
  {
    id: "bakery_chain",
    name: "烘焙品牌拓店组",
    budgetMin: 150000,
    budgetMax: 680000,
    areaMin: 55,
    areaMax: 190,
    preferred: ["street_shop", "corner_shop", "mall_shop", "office_podium"],
    requireExhaust: true,
    requireGas: false,
    priceSensitivity: 50,
    locationSensitivity: 88,
  },
  {
    id: "local_veteran",
    name: "本地餐饮老店",
    budgetMin: 220000,
    budgetMax: 980000,
    areaMin: 90,
    areaMax: 330,
    preferred: ["street_shop", "corner_shop", "community_shop", "detached"],
    requireExhaust: true,
    requireGas: true,
    priceSensitivity: 56,
    locationSensitivity: 82,
  },
];

const BRAND_PREFIXES = [
  "老城",
  "南街",
  "学府",
  "禾味",
  "山海",
  "小满",
  "春和",
  "拾味",
  "炊烟",
  "九里",
  "东巷",
  "百味",
  "青禾",
  "邻里",
  "沐光",
  "巷口",
  "食光",
  "一禾",
  "今味",
  "福来",
];

const BRAND_SUFFIXES = [
  "食堂",
  "小馆",
  "面馆",
  "饭堂",
  "餐厅",
  "厨房",
  "茶铺",
  "咖啡",
  "烘焙",
  "烧烤",
  "火锅",
  "简餐",
  "食集",
  "小厨",
  "餐饮",
];

/**
 * 事件不会固定按顺序出现。
 * system 会根据事件权重、商圈/街道属性和当前天数动态抽取。
 */
const EVENT_TEMPLATES = [
  {
    id: "school_opening",
    name: "高校开学季",
    eligibleDistricts: ["university"],
    minDuration: 12,
    maxDuration: 24,
    weight: 18,
    trafficFactor: 1.18,
    rentPressure: 1.05,
    listingSupplyFactor: 0.92,
    npcDemandFactor: 1.24,
    description: "返校客流明显增加，校门与宿舍区铺位竞争升温",
  },
  {
    id: "graduation",
    name: "毕业季",
    eligibleDistricts: ["university"],
    minDuration: 8,
    maxDuration: 18,
    weight: 11,
    trafficFactor: 1.09,
    rentPressure: 0.98,
    listingSupplyFactor: 1.18,
    npcDemandFactor: 0.92,
    description: "部分学生经营项目退出，转让铺源阶段性增加",
  },
  {
    id: "office_movein",
    name: "大型企业集中入驻",
    eligibleDistricts: ["cbd", "hightech"],
    minDuration: 20,
    maxDuration: 55,
    weight: 8,
    trafficFactor: 1.13,
    rentPressure: 1.07,
    listingSupplyFactor: 0.94,
    npcDemandFactor: 1.18,
    description: "新增办公人口推高工作日餐饮需求",
  },
  {
    id: "roadwork",
    name: "道路施工",
    eligibleDistricts: [
      "university",
      "cbd",
      "hightech",
      "oldtown",
      "village",
      "market",
      "industry",
    ],
    minDuration: 10,
    maxDuration: 45,
    weight: 10,
    trafficFactor: 0.71,
    rentPressure: 0.94,
    listingSupplyFactor: 1.13,
    npcDemandFactor: 0.76,
    description: "施工影响自然客流与门店可见度，部分房东开始让价",
  },
  {
    id: "metro_open",
    name: "轨道交通新站开通",
    eligibleDistricts: ["cbd", "hightech", "oldtown"],
    minDuration: 35,
    maxDuration: 90,
    weight: 4,
    trafficFactor: 1.21,
    rentPressure: 1.11,
    listingSupplyFactor: 0.88,
    npcDemandFactor: 1.28,
    description: "站点周边预期升温，优质铺位挂牌周期缩短",
  },
  {
    id: "night_market",
    name: "夜间消费活动",
    eligibleDistricts: ["university", "oldtown", "village"],
    minDuration: 5,
    maxDuration: 14,
    weight: 13,
    trafficFactor: 1.15,
    rentPressure: 1.02,
    listingSupplyFactor: 0.97,
    npcDemandFactor: 1.16,
    description: "夜间餐饮热度上升，烧烤小吃类经营者积极找铺",
  },
  {
    id: "fire_inspection",
    name: "餐饮消防专项检查",
    eligibleDistricts: [
      "university",
      "cbd",
      "hightech",
      "oldtown",
      "village",
      "market",
      "industry",
    ],
    minDuration: 7,
    maxDuration: 18,
    weight: 8,
    trafficFactor: 0.98,
    rentPressure: 0.97,
    listingSupplyFactor: 1.08,
    npcDemandFactor: 0.89,
    description: "硬件条件不达标的老铺退出概率增加",
  },
  {
    id: "market_upgrade",
    name: "市场改造升级",
    eligibleDistricts: ["market"],
    minDuration: 25,
    maxDuration: 70,
    weight: 7,
    trafficFactor: 0.82,
    rentPressure: 0.96,
    listingSupplyFactor: 1.2,
    npcDemandFactor: 0.77,
    description: "改造期间客流下降，但改造完成后的预期正在抬升",
  },
  {
    id: "factory_orders",
    name: "工业园订单旺季",
    eligibleDistricts: ["industry"],
    minDuration: 15,
    maxDuration: 40,
    weight: 15,
    trafficFactor: 1.12,
    rentPressure: 1.03,
    listingSupplyFactor: 0.96,
    npcDemandFactor: 1.15,
    description: "加班与轮班人口增加，园区餐饮刚需上升",
  },
  {
    id: "factory_slowdown",
    name: "工业园订单回落",
    eligibleDistricts: ["industry"],
    minDuration: 15,
    maxDuration: 45,
    weight: 9,
    trafficFactor: 0.83,
    rentPressure: 0.92,
    listingSupplyFactor: 1.17,
    npcDemandFactor: 0.78,
    description: "部分餐饮经营者收缩，低租金铺源增加",
  },
  {
    id: "tourism_week",
    name: "城市文旅活动周",
    eligibleDistricts: ["cbd", "oldtown", "market"],
    minDuration: 5,
    maxDuration: 10,
    weight: 9,
    trafficFactor: 1.17,
    rentPressure: 1.02,
    listingSupplyFactor: 0.98,
    npcDemandFactor: 1.12,
    description: "游客流量增加，核心街区短期热度上升",
  },
  {
    id: "mall_opening",
    name: "新商业体开业",
    eligibleDistricts: ["cbd", "hightech"],
    minDuration: 25,
    maxDuration: 70,
    weight: 5,
    trafficFactor: 1.08,
    rentPressure: 1.08,
    listingSupplyFactor: 1.06,
    npcDemandFactor: 1.2,
    description: "新商业体释放一批铺位，同时吸引品牌集中进场",
  },
  {
    id: "rent_cooling",
    name: "商业租赁市场降温",
    eligibleDistricts: [
      "university",
      "cbd",
      "hightech",
      "oldtown",
      "village",
      "market",
      "industry",
    ],
    minDuration: 25,
    maxDuration: 80,
    weight: 6,
    trafficFactor: 0.98,
    rentPressure: 0.91,
    listingSupplyFactor: 1.16,
    npcDemandFactor: 0.88,
    description: "空置周期拉长，议价空间增加",
  },
  {
    id: "rent_heating",
    name: "商业租赁市场升温",
    eligibleDistricts: [
      "university",
      "cbd",
      "hightech",
      "oldtown",
      "village",
      "market",
      "industry",
    ],
    minDuration: 20,
    maxDuration: 65,
    weight: 6,
    trafficFactor: 1.04,
    rentPressure: 1.09,
    listingSupplyFactor: 0.91,
    npcDemandFactor: 1.17,
    description: "优质铺位去化加快，房东报价趋强",
  },
];

module.exports = {
  CONFIG,
  TENANT_ARCHETYPES,
  BRAND_PREFIXES,
  BRAND_SUFFIXES,
  EVENT_TEMPLATES,
};
